# Generated by Django 3.1.2 on 2020-12-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201205_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nameOfCategory',
            new_name='name_of_category',
        ),
        migrations.RenameField(
            model_name='listofuniversity',
            old_name='nameOfUnics',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listofuniversity',
            old_name='placeInTheRating',
            new_name='place_in_the_rating',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_choices',
        ),
        migrations.AddField(
            model_name='city',
            name='name_of_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
