# Generated by Django 3.1.2 on 2020-12-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201205_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=900, upload_to='images', width_field=400)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='name_of_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
