# Generated by Django 3.1.2 on 2020-12-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201208_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('place_in_the_rating', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='listofuniversity',
            name='city',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Городa'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='name',
        ),
        migrations.AddField(
            model_name='carousel',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='profession_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Computer Science, IT, management, etc.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.TextField(null=True, verbose_name='Название новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='textOfNews',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок новости'),
        ),
        migrations.DeleteModel(
            name='ListOfUniversity',
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profession'),
        ),
    ]
