# Generated by Django 3.1.2 on 2020-12-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201224_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
    ]
